# This file contains the rules for golangci-lint
# It's a "copy" of 
# with additional rules
# A full example can be found here: https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml

# options for analysis running
run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  deadline: 5m

# override defaults
linters-settings:
  gocyclo:
    # minimal code complexity to report
    min-complexity: 15

# linters to enable in addition to the default linters
linters:
  enable:
    - deadcode
    - dupl
    - gosec
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - ineffassign
    - misspell
    - nakedret
    - staticcheck
    - vet
    - vetshadow
  disable-all: false
