# This file contains the rules for golangci-lint
# It's a "copy" of 
# with additional rules
# A full example can be found here: https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml

# options for analysis running
run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  deadline: 8m
  skip-files:
   - ".*generated.*\\.go"
  skip-dirs:
    - vendor

# override defaults
linters-settings:
  gocyclo:
    # minimal code complexity to report
    min-complexity: 16

# linters to enable
linters:
  enable:
    - deadcode
    - dupl
    - errcheck
    - gosec
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - ineffassign
    - interfacer
    - megacheck
    - misspell
    - nakedret
    - scopelint
    - structcheck
    - typecheck
    - unconvert
    - varcheck
    - vet
    - vetshadow
#    - bodyclose
#    - unparam
  disable:
  disable-all: false
