# This file contains the rules for golangci-lint

# options for analysis running
run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  deadline: 5m

  # which dirs to skip: they won't be analyzed;
  # can use regexp here: generated.*, regexp is applied on full path;
  # default value is empty list, but next dirs are always skipped independently
  # from this option's value:
  #   	vendor$, third_party$, testdata$, examples$, Godeps$, builtin$
  # skip-dirs:
  #   - vendor

# override defaults
linters-settings:
  gocyclo:
    # minimal code complexity to report
    min-complexity: 15

# linters to enable in addition to the default linters
linters:
  enable:
    - deadcode
    - dupl
    - gosec
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - ineffassign
    - misspell
    - nakedret
    - staticcheck
    - vet
    - vetshadow
  disable-all: false

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: "test/integration|_test.go"
      linters:
        - dupl
        - gosec
        - typecheck
