apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        - name: FSS_WCP_VMSERVICE
          value: "false"
          # will be deprecated, story is tracking it
        - name: FSS_WCP_VMSERVICE_UNIFIEDTKG_BYOI
          value: "false"
        - name: FSS_WCP_Unified_TKG
          value: "false"
        - name: FSS_WCP_VMSERVICE_V1ALPHA2
          value: "false"
        - name: VSPHERE_NETWORKING
          value: "false"
        - name: FSS_WCP_FAULTDOMAINS
          value: "true"
        - name: FSS_WCP_INSTANCE_STORAGE
          value: "false"
        - name: FSS_WCP_VMSERVICE_BACKUPRESTORE
          value: "false"
        - name: FSS_WCP_VM_CLASS_AS_CONFIG
          value: "false"
        - name: FSS_WCP_VMSERVICE_PUBLIC_CLOUD_BYOI
          value: "false"
