apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: 2018-12-16T19:42:03Z
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: vmoperator
  resourceVersion: "323"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterroles/edit
  uid: a95c7bff-016a-11e9-aa16-0800278b6504
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - serviceaccounts
  - events
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - impersonate
- apiGroups:
  - "vmoperator.vmware.com"
  resources:
  - virtualmachines
  - virtualmachines/status
  - virtualmachineimages
  - virtualmachineimages/status
  - virtualmachineservices
  - virtualmachineservices/status
  - virtualmachineclasses
  - virtualmachineclasses/status
  verbs:
  - get
  - list
  - watch
  - update
  - patch
