
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.vmoperator.vmware.com
  labels:
    api: vmoperator
    apiserver: "true"
spec:
  version: v1alpha1
  group: vmoperator.vmware.com
  groupPriorityMinimum: 2000
  versionPriority: 10
  service:
    name: vmoperator
    namespace: default
  caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURVRENDQWpnQ0NRQ3A1Vmtob0lRcm5UQU5CZ2txaGtpRzl3MEJBUXNGQURCcU1Rc3dDUVlEVlFRR0V3SjEKYmpFTE1Ba0dBMVVFQ0F3Q2MzUXhDakFJQmdOVkJBY01BV3d4Q2pBSUJnTlZCQW9NQVc4eEN6QUpCZ05WQkFzTQpBbTkxTVNrd0p3WURWUVFERENCMmJXOXdaWEpoZEc5eUxXTmxjblJwWm1sallYUmxMV0YxZEdodmNtbDBlVEFlCkZ3MHhPREV5TVRneU1qQTBNREJhRncweE9URXlNVGd5TWpBME1EQmFNR294Q3pBSkJnTlZCQVlUQW5WdU1Rc3cKQ1FZRFZRUUlEQUp6ZERFS01BZ0dBMVVFQnd3QmJERUtNQWdHQTFVRUNnd0JiekVMTUFrR0ExVUVDd3dDYjNVeApLVEFuQmdOVkJBTU1JSFp0YjNCbGNtRjBiM0l0WTJWeWRHbG1hV05oZEdVdFlYVjBhRzl5YVhSNU1JSUJJakFOCkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXloSnRiYXFHeExvelZBZDhDL09xaUZZdTh1T3oKc215QVRjZ3ltb3U4Z3V5cE1DN3dyRVFrUlJ3SkJaTUtIcDAxcTFWY0QzTW9UK3NTeXgxd0hNMTNFT2hMa3FnOQpRc1RxQWNnUWNQekxrTXlqNHNwbzAvdndTVU5vYkxlaWxiKzdzaldpNml1cUV4NWNjbXpOMUE2VWZxdkJ2TjRsCmxHU2FwVWhyNTJpb0ZPTWVVWFVBWnc4MnAwQklENkVneEFROWdyWDNlV0hUR20zRTZBWHJSdFBBVHBaRitrSWkKZzFTVGU5S3l5Y2xzRzU0Wm15MGw5TUJOOFpRSXlveUQ0c2Q5NFZVK29BS3VETUxlNXhjWGlxUVh0dmNwY2Rxdgo1QUYybW93ZHNsSkdhak8yOUNZeHR1SzBSNnB4aGZqSnVLSU1hZ3pKNTg4MC9GTHhocE9Ta3I4Qm13SURBUUFCCk1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQkM3RXdrcHA5Zlg0U3ZRcGx5S0M1Q21UanpLcnJyTjJTMXFyMVQKMnphdldFWCtnNmJpWWpUenFMNWJ3YXZFV09jUU9PY0ZOOHFYQzhnbFFSMFJZa3RzVnB6WDdSZUNORzhYczdLdgozL1NPcUdqSjZ0bDBQa3ZUVkJscVRMNVhmNmo3ZGlsRGVFYnFpbkFOUlQwL2ZPWXFwbTBsQldiSUVDYVViN3JOCjg1OGUrendyLzFyT2xlMlBWRldyaWlQRXRraTdVZHVhTGZqYTJ2bStKd2tLaU5aT2RPQ2F6bWRnS3A3UHhDWmsKN3RPYU9iZjAzVXhydmxMZWIzeHNiTWJGeDEwY2NreVJQSUJaQlJGNGk2YmtBZ3czR29xSzZybTNvUFY3N2pLNwpIekJpdm93U0lmcjNEc25DdjJDK05kQmJoaGp1aWlIeU03c2hIcURDSEVQSndTdHkKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
---
apiVersion: v1
kind: Service
metadata:
  name: vmoperator
  namespace: default
  labels:
    api: vmoperator
    apiserver: "true"
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    api: vmoperator
    apiserver: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vmoperator
  namespace: default
  labels:
    api: vmoperator
    apiserver: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      api: vmoperator
      apiserver: "true"
  template:
    metadata:
      labels:
        api: vmoperator
        apiserver: "true"
    spec:
      containers:
      - name: apiserver
        image: vmoperator:vmop
        imagePullPolicy: Never
        volumeMounts:
        - name: apiserver-certs
          mountPath: /apiserver.local.config/certificates
          readOnly: true
        command:
        - "./apiserver"
        args:
        - "--etcd-servers=http://etcd-svc:2379"
        - "--tls-cert-file=/apiserver.local.config/certificates/tls.crt"
        - "--tls-private-key-file=/apiserver.local.config/certificates/tls.key"
        - "--audit-log-path=-"
        - "--audit-log-maxage=0"
        - "--audit-log-maxbackup=0"
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        livenessProbe:
          httpGet:
            path: /healthz
            port: 443
            scheme: HTTPS
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 15
        resources:
          requests:
            cpu: 100m
            memory: 20Mi
          limits:
            cpu: 100m
            memory: 30Mi
      - name: controller
        image: vmoperator:vmop
        imagePullPolicy: Never
        command:
        - "./manager"
        args:
          - "health-addr=:49201"
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        livenessProbe:
          httpGet:
            path: /healthz
            port: 49201
          initialDelaySeconds: 25
          periodSeconds: 3
        resources:
          requests:
            cpu: 100m
            memory: 20Mi
          limits:
            cpu: 100m
            memory: 30Mi
      volumes:
      - name: apiserver-certs
        secret:
          secretName: vmoperator
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: etcd
  namespace: default
spec:
  serviceName: "etcd"
  replicas: 1
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: etcd
        image: quay.io/coreos/etcd:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 100m
            memory: 256Mi
        env:
        - name: ETCD_DATA_DIR
          value: /etcd-data-dir
        command:
        - /usr/local/bin/etcd
        - --listen-client-urls
        - http://0.0.0.0:2379
        - --advertise-client-urls
        - http://localhost:2379
        ports:
        - containerPort: 2379
        volumeMounts:
        - name: etcd-data-dir
          mountPath: /etcd-data-dir
        readinessProbe:
          httpGet:
            port: 2379
            path: /health
          failureThreshold: 1
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        livenessProbe:
          httpGet:
            port: 2379
            path: /health
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
  volumeClaimTemplates:
  - metadata:
     name: etcd-data-dir
     annotations:
        volume.beta.kubernetes.io/storage-class: standard
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
         storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: etcd-svc
  namespace: default
  labels:
    app: etcd
spec:
  ports:
  - port: 2379
    name: etcd
    targetPort: 2379
  selector:
    app: etcd
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: vmoperator
  namespace: default
  labels:
    api: vmoperator
    apiserver: "true"
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURSakNDQWk0Q0NRQ3RMNG9RZHVnMXZUQU5CZ2txaGtpRzl3MEJBUVVGQURCcU1Rc3dDUVlEVlFRR0V3SjEKYmpFTE1Ba0dBMVVFQ0F3Q2MzUXhDakFJQmdOVkJBY01BV3d4Q2pBSUJnTlZCQW9NQVc4eEN6QUpCZ05WQkFzTQpBbTkxTVNrd0p3WURWUVFERENCMmJXOXdaWEpoZEc5eUxXTmxjblJwWm1sallYUmxMV0YxZEdodmNtbDBlVEFlCkZ3MHhPREV5TVRneU1qQTBNREZhRncweE9URXlNVGd5TWpBME1ERmFNR0F4Q3pBSkJnTlZCQVlUQW5WdU1Rc3cKQ1FZRFZRUUlEQUp6ZERFS01BZ0dBMVVFQnd3QmJERUtNQWdHQTFVRUNnd0JiekVMTUFrR0ExVUVDd3dDYjNVeApIekFkQmdOVkJBTU1Gblp0YjNCbGNtRjBiM0l1WkdWbVlYVnNkQzV6ZG1Nd2dnRWlNQTBHQ1NxR1NJYjNEUUVCCkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDdTJVcmxFSGpsR3pINitTODQwOGozWkVXTHpNT2NDamc1bjFqOExZWFMKQ3VMY0ZxN0s5dTJacmlMUGN0UVdVVEhkaytZUTJla01kQUdoc2Z3WTZzT1BkYmxwdmNRYmErYWdEaGtjc1pwbApKUS9WTUJJaUNqbE9zRDVlQjloRTNmMHV5UHQzbURZQjEwWGZ1VmlpWVQrN2FHL1FnV3EwYlgraFlKUTRhZ3RkCmJ1dmsvVGVZdnVjSFFoWW5vb2dhUTFQcklRSUJuVVlGUGpPN2V5MkVSMS9IbjZsR2FMQ0d5SGpsYkhmb0NPQ00KMGRxT0lSZVNwUGthRzhYRDViTU5ZSTZTOWtnRTFzTVZoQkZya29Ic0JISk1nYWRNS0wxODJoa0JiaGErK2hQUAp2T1Z0Mm1nL3ZrRC8wdFYyZ2FMbHFsMTk0NEJZcWRvOVVCdzJOM3B4LzhtRkFnTUJBQUV3RFFZSktvWklodmNOCkFRRUZCUUFEZ2dFQkFBeFFBNDMvYUg5UFBBN2IyVy9pd0NSR0hCcVovcjJ5d0JZTWJLeE9XbC81SndwL21YRnkKNmVnVjBpa2daeUw5bUNUM1hxUmxvOERaVEhJbmZMNUtqNnVsNWZYY0NwMHR4UzdyRzVkVHFlcFFsdFduZzB0WAp5eGttbmMxUFVTZndLOXBjUndUS3JvUTc2UTQvWjZRY1JBNjR0ci9UcGhKWVFCQmRMYTh1SXphRW03dzZvcjFVCnRjeVlsOGIvWUR1ZVVrODBsVU1NSm9HWHFDUzN2MjZaTGg1eVdEVmR3ZEV1U3RXR1RqYkZMNGY5Rk5KQVp4RUoKZU9IcEN4SGV6eXlVZkxtVUdXd3VCUXlzNHVnYmFUUXBrcTZOSnljc250ckd6dytSdE03cWZPM3BJa01DSWt3VQppUmsrTVhpZmkwL2U1Z29yM1BPelFwTDdEdDB4VTlvd3U2cz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRQ3UyVXJsRUhqbEd6SDYKK1M4NDA4ajNaRVdMek1PY0NqZzVuMWo4TFlYU0N1TGNGcTdLOXUyWnJpTFBjdFFXVVRIZGsrWVEyZWtNZEFHaApzZndZNnNPUGRibHB2Y1FiYSthZ0Roa2NzWnBsSlEvVk1CSWlDamxPc0Q1ZUI5aEUzZjB1eVB0M21EWUIxMFhmCnVWaWlZVCs3YUcvUWdXcTBiWCtoWUpRNGFndGRidXZrL1RlWXZ1Y0hRaFlub29nYVExUHJJUUlCblVZRlBqTzcKZXkyRVIxL0huNmxHYUxDR3lIamxiSGZvQ09DTTBkcU9JUmVTcFBrYUc4WEQ1Yk1OWUk2UzlrZ0Uxc01WaEJGcgprb0hzQkhKTWdhZE1LTDE4MmhrQmJoYSsraFBQdk9WdDJtZy92a0QvMHRWMmdhTGxxbDE5NDRCWXFkbzlVQncyCk4zcHgvOG1GQWdNQkFBRUNnZ0VCQUtkdjhGZXhVWVJjYVoxa0dNTjdsQnpNaWdqWk9vem9BSFcxMGJvVVFlMGwKZlorem5RbENNOEFTVU1XRnVmSHhLU1orSmpnRzVUU0d0clZJUXhqOVgrNjJscXJiRGJ3UXRSYWF5Wk4veEZHTgpqejdoUE13YUxFemRXNndpS1FteDUyMXhDOWE0RFNmd0picWJ2SFFyV3FPMTNEVzRhUjJGS2s2NHROZmRQU3JuCm8yTWpycVRVRmQ4WkRyekZWU2Y3c3BxSlJleExuWUswYXh1YnQxeHRIMlAwbHZSZGQybjRFUEk2ZU1KOTB2bEEKRXMrZ0l1cVZ5eHpjZnI5bGVmRTZvWDB0bFdnck1ySHlsSnJvd1phZ293dlltYkRkdGZQQy82RVNUY01JZHcrWgpodURTdDAyZnEyaVduUXFxS21qVGQ0K3NXczBMZnptQlp3bS82UDdaUUlFQ2dZRUEyWXJBK2VWaHpZd3VZZFZHClY1MU02VXoydWNQandtcklZSHNCUDZrdWVRNUY3REFYZEpUSXh0dXZWRUdJaWxaa29HVEcxUkJPRUhtN25jWmEKQ0ljaU1FOHl1QkNXeFdQOVpRTTZNSzBiYzhBcEw2UHBPWWUzSzNFSjVDUW4yVkJvSjYyZ29YbUYra1M0cW94bApIWFlqeWlpL2xOUWYvVUQ1S3VPM2RjeVZ5aVVDZ1lFQXpjSmg3TElrRzQxZEpTVnBpbVBmWlU5YWU2WEw2VjRLCmZSYkkyUGRaNkEvSVYvdWVMKzB3Qm1KbmlRK2E0Ykp1VmlJVWExekh4VGFSek9lV1BlaE1kbkF1VDFSNk9wTEkKN1krZDkwV0VjUjJuRDYzZEJzT2J0bWJ4cUViMFBWZ21Ib2kvWDkrbUpwUVFyMnc4NFdIeFcwVFhNTFNxcEVsSAo4eVFUZW9BWTgrRUNnWUVBbHZMYjBzcmk0WURxMGtIdUxHOWU1ZWZjcjZ3SWgyZ1hJRE5aKzNXR1pNT05xMFQzCmtaS0grc3lIVFZ5bnhPNExwdXdtdDhNM2wrRVFXWHRBRC9qTXRWN1BINytMRHU3QjdteWQzUmJSSExGeklyYUcKNTcrUFR4cUJ0WWVOQ3hMckl0VXN4NzhPUTBtYUplV0RhRDBJdW9jcDRMaU1kZXUydVpjSFB6czFtTzBDZ1lCdAozUm1PV2J2LzNpWmEvRFB6U2NweGZNSnlmUjk0MXRiQTNkYVdTdFI5blZlNjZzWVhEdzF5aXo1L0o0N3FiZXlPCkh4cEtEVHM1cVI2R2l5MWtsdEdrOTljeVVvZ0ZHSFVpcTJtTUsxbEJVTFR3SVVTQUpSZlNkL3NXZi9SUGdPNngKcFJDU0w0ZTIxNTVsSEdVUmJzdUJrU3RaZlU0VDlIRHZlVmJSTk82ZDRRS0JnR2N4YncwUTV0aVJoNjJDaWVUbwp4OTNiQ3BVVzViRzhIb3czZU5tRGl4WHpvazZ1YXFIMi9uZUJaWTBkbzEwUk1TUXR5L1JYcFJLY0F1Ti9EaHY4CmRXWFE2NjNaaVE4bFJHSW5JNFVSMEtFSUlHaWRBNTBUSkRXaFIvTVgxL0FrNXJSVm5ibmdkenhmQmMvaFdYa0YKSldJMTNHS0d6ZGVaZlNxRWN1WEhSMEk0Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
