apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../local

resources:
- sc.yaml
- lb-xds.yaml

patches:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: vmware-system-vmop-controller-manager
    namespace: vmware-system-vmop
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
- target:
    group: apps
    version: v1
    kind: Deployment
    name: vmware-system-vmop-controller-manager
    namespace: vmware-system-vmop
  path: remove-node-selector-patch.yaml
- target:
    group: apps
    version: v1
    kind: Deployment
    name: vmware-system-vmop-web-console-validator
    namespace: vmware-system-vmop
  path: remove-node-selector-patch.yaml

patchesStrategicMerge:
  - vcsim-patch.yaml
