# Add storage classes and resource quota to local vcsim deployment
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cp-storage-class 
provisioner: kubernetes.io/vsphere-volume
parameters:
    storagePolicyID: "test-policy-id"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: worker-storage-class
provisioner: kubernetes.io/vsphere-volume
parameters:
    storagePolicyID: "test-policy-id"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: default-rq
  namespace: default
spec:
  hard:
   cp-storage-class.storageclass.storage.k8s.io/requests.storage: 1Gi
   worker-storage-class.storageclass.storage.k8s.io/requests.storage: 1Gi

