# Patch to start a local deployment against vcsim
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vmoperator-controller
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: controller
        env:
        # Add extraConfig to the VirtualMachines to tell vcsim to run a container per VM
        - name: "JSON_EXTRA_CONFIG"
          value: |
            {"RUN.container":"[\"--privileged\", \"-v=/lib/modules:/lib/modules:ro\", \"{{.ImageName}}\"]"}
