
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: virtualmachineclasses.vmoperator.vmware.com
spec:
  group: vmoperator.vmware.com
  names:
    kind: VirtualMachineClass
    plural: virtualmachineclasses
    shortNames:
    - vmclass
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: VirtualMachineClass is the Schema for the virtualmachineclasses
        API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: VirtualMachineClassSpec defines the desired state of VirtualMachineClass
          properties:
            hardware:
              properties:
                cpus:
                  format: int64
                  type: integer
                memory:
                  type: string
              type: object
            policies:
              properties:
                resources:
                  properties:
                    limits:
                      properties:
                        cpu:
                          type: string
                        memory:
                          type: string
                      type: object
                    requests:
                      properties:
                        cpu:
                          type: string
                        memory:
                          type: string
                      type: object
                  type: object
              type: object
          type: object
        status:
          description: VirtualMachineClassStatus defines the observed state of VirtualMachineClass
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
