
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: virtualmachinesetresourcepolicies.vmoperator.vmware.com
spec:
  group: vmoperator.vmware.com
  names:
    kind: VirtualMachineSetResourcePolicy
    plural: virtualmachinesetresourcepolicies
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: VirtualMachineSetResourcePolicy is the Schema for the virtualmachinesetresourcepolicies
        API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: VirtualMachineSetResourcePolicySpec defines the desired state
            of VirtualMachineSetResourcePolicy
          properties:
            clustermodules:
              items:
                description: ClusterModuleSpec defines a ClusterModule in VC.
                properties:
                  groupname:
                    type: string
                required:
                - groupname
                type: object
              type: array
            folder:
              description: Folder defines a Folder
              properties:
                name:
                  type: string
              type: object
            resourcepool:
              description: ResourcePoolSpec defines a Resource Group
              properties:
                limits:
                  properties:
                    cpu:
                      type: string
                    memory:
                      type: string
                  type: object
                name:
                  type: string
                reservations:
                  properties:
                    cpu:
                      type: string
                    memory:
                      type: string
                  type: object
              type: object
          type: object
        status:
          description: VirtualMachineSetResourcePolicyStatus defines the observed
            state of VirtualMachineSetResourcePolicy
          properties:
            clustermodules:
              items:
                properties:
                  groupname:
                    type: string
                  moduleUUID:
                    type: string
                required:
                - groupname
                - moduleUUID
                type: object
              type: array
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
