name: pre-commit

on: [push, pull_request]

jobs:

  lint-go:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.19.3'
    - name: Check out code
      uses: actions/checkout@v3
    - name: Lint Go
      run: make lint-go-full

  lint-markdown:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.19.3'
    - name: Check out code
      uses: actions/checkout@v3
    - name: Lint Markdown
      run: make lint-markdown

  lint-shell:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.19.3'
    - name: Check out code
      uses: actions/checkout@v3
    - name: Lint Shell
      run: make lint-shell

  verify-codegen:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.19.3'
    - name: Check out code
      uses: actions/checkout@v3
    - name: Lint
      run: make verify-codegen

  build-manager:
    needs:
    - lint-go
    - lint-markdown
    - lint-shell
    - verify-codegen
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.19.3'
    - name: Check out code
      uses: actions/checkout@v3
    - name: Build Manager
      run: make manager-only

  build-web-console-validator:
    needs:
    - lint-go
    - lint-markdown
    - lint-shell
    - verify-codegen
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.19.3'
    - name: Check out code
      uses: actions/checkout@v3
    - name: Build Web Console Validator
      run: make web-console-validator-only

  unit-test:
    needs:
    - build-manager
    - build-web-console-validator
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.19.3'
    - name: Check out code
      uses: actions/checkout@v3
    - name: Unit Test
      run: make test

  integration-test:
    needs:
    - build-manager
    - build-web-console-validator
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.19.3'
    - name: Check out code
      uses: actions/checkout@v3
    - name: Integration Test
      run: make test-integration